export const products = [
  //   {
  //     title: "Monitor XL",
  //     description: "Samsung",
  //     price: 80000,
  //     category: "Hardware",
  //     code: "5",
  //     stock: 12,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Teclado Inalámbrico",
  //     description: "Logitech",
  //     price: 4500,
  //     category: "Hardware",
  //     code: "7",
  //     stock: 25,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Impresora Multifuncional",
  //     description: "Epson",
  //     price: 12000,
  //     category: "Hardware",
  //     code: "11",
  //     stock: 8,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Silla de Oficina Ergonómica",
  //     description: "IKEA",
  //     price: 3500,
  //     category: "Mobiliario",
  //     code: "18",
  //     stock: 15,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Portátil Ultradelgado",
  //     description: "Dell",
  //     price: 55000,
  //     category: "Hardware",
  //     code: "23",
  //     stock: 10,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Escritorio de Madera",
  //     description: "Home Office",
  //     price: 8000,
  //     category: "Mobiliario",
  //     code: "29",
  //     stock: 20,
  //     status: true,
  //     thumbnails: [],
  //   },
  //   {
  //     title: "Mouse Óptico",
  //     description: "HP",
  //     price: 1500,
  //     category: "Hardware",
  //     code: "35",
  //     stock: 30,
  //     status: true,
  //     thumbnails: [],
  //   },

  {
    title: "Laptop Gaming",
    description: "ASUS",
    price: 75000,
    category: "Hardware",
    code: "41",
    stock: 5,
    status: true,
    thumbnails: [],
  },
  {
    title: "Mesa de Conferencia",
    description: "Ofitech",
    price: 6000,
    category: "Mobiliario",
    code: "47",
    stock: 18,
    status: true,
    thumbnails: [],
  },
  {
    title: "Tableta Gráfica",
    description: "Wacom",
    price: 3500,
    category: "Hardware",
    code: "53",
    stock: 15,
    status: true,
    thumbnails: [],
  },
  {
    title: "Silla Gamer",
    description: "Acer",
    price: 2800,
    category: "Mobiliario",
    code: "59",
    stock: 10,
    status: true,
    thumbnails: [],
  },
  {
    title: "Monitor Curvo",
    description: "LG",
    price: 6500,
    category: "Hardware",
    code: "65",
    stock: 22,
    status: true,
    thumbnails: [],
  },
  {
    title: "Calculadora Científica",
    description: "Casio",
    price: 450,
    category: "Accesorios",
    code: "71",
    stock: 50,
    status: true,
    thumbnails: [],
  },
  {
    title: "Router Wi-Fi",
    description: "TP-Link",
    price: 2500,
    category: "Hardware",
    code: "77",
    stock: 12,
    status: true,
    thumbnails: [],
  },
  {
    title: "Lámpara de Escritorio",
    description: "Philips",
    price: 1200,
    category: "Iluminación",
    code: "83",
    stock: 30,
    status: true,
    thumbnails: [],
  },

  {
    title: "Mochila para Portátil",
    description: "Marca: Samsonite",
    price: 3500,
    category: "Accesorios",
    code: "89",
    stock: 15,
    status: true,
    thumbnails: [],
  },
  {
    title: "Calculadora Gráfica",
    description: "Texas Instruments",
    price: 650,
    category: "Accesorios",
    code: "95",
    stock: 20,
    status: true,
    thumbnails: [],
  },
  {
    title: "Auriculares Bluetooth",
    description: "Sony",
    price: 2500,
    category: "Accesorios",
    code: "101",
    stock: 18,
    status: true,
    thumbnails: [],
  },
  {
    title: "Escáner de Documentos",
    description: "Epson",
    price: 1800,
    category: "Hardware",
    code: "107",
    stock: 8,
    status: true,
    thumbnails: [],
  },
  {
    title: "Caja de Almacenamiento",
    description: "Plástico Transparente",
    price: 450,
    category: "Accesorios",
    code: "113",
    stock: 40,
    status: true,
    thumbnails: [],
  },
  {
    title: "Papelera de Oficina",
    description: "Metálica",
    price: 1200,
    category: "Mobiliario",
    code: "119",
    stock: 25,
    status: true,
    thumbnails: [],
  },
  {
    title: "Mousepad Gaming",
    description: "Razer",
    price: 600,
    category: "Accesorios",
    code: "125",
    stock: 30,
    status: true,
    thumbnails: [],
  },
  {
    title: "Cámara Web HD",
    description: "Logitech",
    price: 2800,
    category: "Accesorios",
    code: "131",
    stock: 10,
    status: true,
    thumbnails: [],
  },
  {
    title: "Alfombrilla para Silla",
    description: "Protector de Suelo",
    price: 1200,
    category: "Mobiliario",
    code: "137",
    stock: 15,
    status: true,
    thumbnails: [],
  },
  {
    title: "Lámpara de Escritorio LED",
    description: "Luz Ajustable y Regulable",
    price: 800,
    category: "Accesorios",
    code: "143",
    stock: 22,
    status: true,
    thumbnails: [],
  },
  {
    title: "Ratón Inalámbrico Ergonómico",
    description: "Logitech MX Master 3",
    price: 2500,
    category: "Accesorios",
    code: "149",
    stock: 12,
    status: true,
    thumbnails: [],
  },
  {
    title: "Impresora Multifunción",
    description: "HP OfficeJet Pro",
    price: 4500,
    category: "Hardware",
    code: "155",
    stock: 9,
    status: true,
    thumbnails: [],
  },
  {
    title: "Pizarra Blanca",
    description: "Tamaño Grande",
    price: 900,
    category: "Accesorios",
    code: "161",
    stock: 18,
    status: true,
    thumbnails: [],
  },
  {
    title: "Mesa de Escritorio",
    description: "Diseño Moderno",
    price: 2200,
    category: "Mobiliario",
    code: "167",
    stock: 7,
    status: true,
    thumbnails: [],
  },
  {
    title: "Teléfono VoIP",
    description: "Grandstream",
    price: 1200,
    category: "Accesorios",
    code: "173",
    stock: 14,
    status: true,
    thumbnails: [],
  },
  {
    title: "Kit de Limpieza de Computadora",
    description: "Incluye Cepillos y Aire Comprimido",
    price: 300,
    category: "Accesorios",
    code: "179",
    stock: 35,
    status: true,
    thumbnails: [],
  },
  {
    title: "Silla Ergonómica de Oficina",
    description: "Respaldo Ajustable",
    price: 1800,
    category: "Mobiliario",
    code: "185",
    stock: 10,
    status: true,
    thumbnails: [],
  },
  {
    title: "Teclado Mecánico para Gaming",
    description: "RGB, Switches Cherry MX",
    price: 2200,
    category: "Accesorios",
    code: "191",
    stock: 16,
    status: true,
    thumbnails: [],
  },
  {
    title: "Router Inalámbrico de Alta Velocidad",
    description: "Marca: TP-Link",
    price: 1200,
    category: "Accesorios",
    code: "197",
    stock: 11,
    status: true,
    thumbnails: [],
  },
];
